# Generated by Django 5.2.8 on 2025-11-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('product', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=120)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('subscription_type', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free'), ('In Arrears', 'In arrears')], default='Paid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'customer subscription',
                'verbose_name_plural': 'customer subscriptions',
                'ordering': ['external_id'],
            },
        ),
    ]
