# Generated by Django 5.2.8 on 2025-11-20 04:36

from datetime import datetime
from zoneinfo import ZoneInfo

from django.db import migrations


def seed_customers(apps, schema_editor):
    Customer = apps.get_model("portal", "CustomerSubscription")
    ph_tz = ZoneInfo("Asia/Manila")
    seed_data = [
        {
            "external_id": "INV-2045",
            "product": "PlugHub Inventory",
            "email": "fleet.ops@plughub.com",
            "username": "fleet-ops",
            "last_login": datetime(2025, 1, 14, 14, 33, tzinfo=ph_tz),
            "subscription_type": "Yearly",
            "status": "Paid",
        },
        {
            "external_id": "QMS-9934",
            "product": "PlugHub Queueing",
            "email": "queues@plughub.com",
            "username": "queue-master",
            "last_login": datetime(2025, 1, 20, 10, 5, tzinfo=ph_tz),
            "subscription_type": "Monthly",
            "status": "Paid",
        },
        {
            "external_id": "PCX-5533",
            "product": "Payment Checker",
            "email": "finance.audit@plughub.com",
            "username": "audit-team",
            "last_login": datetime(2025, 1, 22, 8, 12, tzinfo=ph_tz),
            "subscription_type": "Pilot",
            "status": "Free",
        },
        {
            "external_id": "INV-8721",
            "product": "PlugHub Inventory",
            "email": "warehouse@plughub.com",
            "username": "wh-admin",
            "last_login": datetime(2025, 1, 18, 19, 52, tzinfo=ph_tz),
            "subscription_type": "One-time",
            "status": "Paid",
        },
    ]
    for entry in seed_data:
        Customer.objects.update_or_create(
            external_id=entry["external_id"],
            defaults=entry,
        )


def remove_customers(apps, schema_editor):
    Customer = apps.get_model("portal", "CustomerSubscription")
    ids = ["INV-2045", "QMS-9934", "PCX-5533", "INV-8721"]
    Customer.objects.filter(external_id__in=ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_customers, remove_customers),
    ]
