# Generated by Django 5.2.8 on 2025-11-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='date_consumed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
