# Generated by Django 5.2.8 on 2025-11-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_seed_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(max_length=80, unique=True)),
                ('payment_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(max_length=40)),
                ('used', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'payment record',
                'verbose_name_plural': 'payment records',
                'ordering': ['-created_at'],
            },
        ),
    ]
